# This file is part of project "BlockMacro"
# "plugin.yml" made at 2021 - 2 - 22 from computer named "hrd201-9"
#
# Copyright (C) 2021 Hyun-Ku Lee
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

name: BlockMacro
version: ${project.version}
author: Hyun-Ku Lee
description: Plugin, Anti-Macro, Modifiable Solution, JDK11 "BlockMacro"
website: https://github.com/LeeHyKu/BlockMacro

api-version: 1.12
main: me.hklee.blockmacro.Blockmacro

permissions:
  blockmacro.*:
    default: op
    description: 루트 퍼미션
    children:
      blockmacro.ignore: true
  blockmacro.ignore:
    default: op
    description: 안티메크로의 영향을 받지 않음